### ISSUE TITLE
Add an automatic `pip` environment

### ISSUE THREAD

**Issue by Yoshanuikabundi** [Yoshanuikabundi/snakes_on_a_plane#14]
There should be a special environment called `"pip"` that installs Pip and the earliest NEP29-compatible minor version of Python via conda-forge, and then installs the local package and its dependencies via PIP (with the existing code). This way, users can use SOAP with any project that conforms to modern Python packaging standards without writing a Conda environment. This environment would basically be equivalent to:

soap.toml:
```toml
[envs]
pip = "pip-env.yml"
```

pip-env.yml:
```yml
channels: 
 - conda-forge
dependencies:
 - python=3.9
 - pip
```

If no environments are specified by the user, the `pip` environment could be used as the default environment.
