### ISSUE TITLE
An environment file with an empty channel list raises an obscure error

### ISSUE THREAD

**Issue by Yoshanuikabundi** [Yoshanuikabundi/snakes_on_a_plane#6]
Example YAML file:

```yaml
name: projectname-docs
channels:
dependencies:
  # Base depends
  - python
  - pip

  # Documentation
  - myst-parser==0.18.1
  - sphinx<6
  - sphinx-notfound-page
  - autodoc-pydantic
  - sphinx-click

  #  Pip-only installs
  - pip:
    - git+https://github.com/openforcefield/openff-sphinx-theme.git@main
```
